from __future__ import annotations

import json
import os
import shutil
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

from .config import OUTPUT_ROOT, PUBLIC_ROUTES, RouteDefinition
from .pipeline import validate_existing


def approve(route: RouteDefinition, reviewer: str, pdf_reviewed: bool) -> Path:
    if not pdf_reviewed:
        raise ValueError("La aprobación requiere confirmar la revisión del PDF oficial")
    report = validate_existing(route)
    if not report.get("quality_pass"):
        raise ValueError("La geometría no supera la validación automática")
    approval = {
        "route": route.slug,
        "artifact_sha256": report["artifact_sha256"],
        "reviewer": reviewer,
        "pdf_reviewed": True,
        "approved_at": datetime.now(timezone.utc).isoformat(),
    }
    target = OUTPUT_ROOT / route.slug / "approval.json"
    target.write_text(json.dumps(approval, ensure_ascii=False, indent=2), encoding="utf-8")
    return target


def publish(route: RouteDefinition, skip_supabase: bool = False) -> Path:
    output = OUTPUT_ROOT / route.slug
    report = validate_existing(route)
    approval_path = output / "approval.json"
    if not approval_path.is_file():
        raise PermissionError("Falta aprobación manual; ejecute approve después de revisar review.html")
    approval = json.loads(approval_path.read_text(encoding="utf-8"))
    if approval.get("artifact_sha256") != report.get("artifact_sha256"):
        raise PermissionError("La geometría cambió después de aprobarse")
    source = output / f"{route.code}.geojson"
    PUBLIC_ROUTES.mkdir(parents=True, exist_ok=True)
    temporary = PUBLIC_ROUTES / f".{route.code}.geojson.tmp"
    shutil.copyfile(source, temporary)
    if not skip_supabase:
        try:
            _publish_supabase(route, report, approval, json.loads(source.read_text(encoding="utf-8")))
        except Exception:
            temporary.unlink(missing_ok=True)
            raise
    temporary.replace(PUBLIC_ROUTES / f"{route.code}.geojson")
    _update_web_index(route, report["artifact_sha256"])
    return PUBLIC_ROUTES / f"{route.code}.geojson"


def _update_web_index(route: RouteDefinition, artifact_sha256: str) -> None:
    index_path = PUBLIC_ROUTES / "index.json"
    routes: list[dict] = []
    if index_path.is_file():
        try:
            current = json.loads(index_path.read_text(encoding="utf-8"))
            # Old indexes were generated by experimental matchers and can
            # expose routes that have not passed the Valhalla publication gate.
            if current.get("algorithm") == "valhalla-kml-corridor-v1":
                routes = list(current.get("routes") or [])
        except (json.JSONDecodeError, OSError):
            routes = []
    routes = [item for item in routes if str(item.get("id")) != route.code]
    routes.append(
        {
            "id": route.code,
            "name": route.name,
            "color": route.color,
            "transportType": "Combi" if route.transport_type == "combi" else "Camión",
            "colorName": "Amarillo",
            "colorLetter": "C" if route.transport_type == "combi" else "A",
            "geojsonFile": f"/routes/{route.code}.geojson?v={artifact_sha256[:12]}",
            "artifactSha256": artifact_sha256,
        }
    )
    payload = {
        "type": "routes-index",
        "generatedAt": datetime.now(timezone.utc).isoformat(),
        "algorithm": "valhalla-kml-corridor-v1",
        "routes": sorted(routes, key=lambda item: item["name"]),
    }
    temporary = index_path.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    temporary.replace(index_path)


def _publish_supabase(route: RouteDefinition, report: dict, approval: dict, geojson: dict) -> None:
    url = os.environ.get("SUPABASE_URL") or os.environ.get("NEXT_PUBLIC_SUPABASE_URL")
    key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY") or os.environ.get("SUPABASE_SECRET_KEY")
    if not url or not key:
        print("SUPABASE_SERVICE_ROLE_KEY no está definida. Intentando publicación directa vía base de datos...")
        import subprocess
        import tempfile
        
        payload = {
            "route_code": route.code,
            "artifact_sha256": report["artifact_sha256"],
            "geometry": geojson,
            "metrics": report,
            "source_metadata": report.get("metadata", {}),
            "reviewer": approval["reviewer"],
        }
        
        with tempfile.NamedTemporaryFile(mode="w", delete=False, suffix=".json", encoding="utf-8") as temp_file:
            json.dump(payload, temp_file, ensure_ascii=False)
            temp_path = Path(temp_file.name)
            
        try:
            node_script = Path(__file__).resolve().parents[1] / "apps" / "api" / "db_publish_fallback.js"
            res = subprocess.run(
                ["node", str(node_script), str(temp_path)],
                capture_output=True,
                text=True,
                cwd=str(Path(__file__).resolve().parents[1] / "apps" / "api")
            )
            if res.returncode != 0:
                raise RuntimeError(f"Falló la publicación por base de datos: {res.stderr}\n{res.stdout}")
            print(res.stdout.strip())
        finally:
            temp_path.unlink(missing_ok=True)
        return

    payload = json.dumps(
        {
            "p_route_code": route.code,
            "p_artifact_sha256": report["artifact_sha256"],
            "p_geometry": geojson,
            "p_metrics": report,
            "p_source_metadata": report.get("metadata", {}),
            "p_reviewer": approval["reviewer"],
        }
    ).encode("utf-8")
    request = urllib.request.Request(
        f"{url.rstrip('/')}/rest/v1/rpc/publish_validated_route_artifact",
        data=payload,
        method="POST",
        headers={"apikey": key, "Authorization": f"Bearer {key}", "Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=60) as response:
            if response.status >= 300:
                raise RuntimeError(f"Supabase respondió HTTP {response.status}")
    except urllib.error.HTTPError as error:
        detail = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"Falló la publicación en Supabase: HTTP {error.code}: {detail}") from error
